### ISSUE TITLE
Consider add the .gitignore file

### ISSUE THREAD

**Issue by SummerRegicide** [DL444/OfficeDeploy#1]
Add the *`.gitignore`* to gain the better experience. Refer to [Visual Studio gitignore](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) for more details.
In general, contributors do **NOT** care if executable files are included in the repository. All they focus on is your code.
Using [tag](https://git-scm.com/docs/git-tag) function provided in *Git* to control your releases.

**Comment by DL444** [comment]
Fixed in the last commit.
